// Fake edital data for the Radar PNCP UI kit (recreation only).
import type { Empresa, Edital, RadarData } from './types'

export const empresa: Empresa = {
  nome: 'AI Solution Exp LTDA - ME',
  cnpj: '53.075.641/0001-71',
  area: 'Automações, agentes de IA, integrações e atendimento automatizado',
}

export const editais: Edital[] = [
  {
    id: 'op-418',
    orgao: 'Prefeitura Municipal de Sobral',
    cidade: 'Sobral',
    estado: 'CE',
    titulo:
      'Contratação de plataforma de atendimento digital com chatbot e IA para a central do cidadão',
    objetoCurto: 'Plataforma de atendimento digital · chatbot · IA',
    modalidade: 'Dispensa eletrônica',
    publicado: '02/06/2026',
    prazo: '14/06/2026',
    valor: 'R$ 62.000',
    valorNum: 62000,
    score: 87,
    status: 'forte',
    urgente: true,
    recomendacao:
      'Participar — objeto fortemente compatível com automação, IA e atendimento digital.',
    tags: ['chatbot', 'IA', 'atendimento digital', 'API'],
    resumo:
      'O município quer implantar um canal único de atendimento ao cidadão com chatbot integrado ao portal e ao WhatsApp, com painel de acompanhamento de demandas. Escopo cobre implantação, treinamento e 12 meses de manutenção.',
    porQueCombina: [
      'Objeto central é atendimento automatizado via chatbot',
      'Integração com WhatsApp e APIs — domínio direto da AI Solution',
      'CNAE de licenciamento de software compatível',
      'Dispensa eletrônica: ciclo curto e menos burocracia',
    ],
    porQueNao: [
      'Exige atestado de capacidade técnica de projeto similar',
      'Prazo de implantação de 30 dias é apertado',
    ],
    documentos: [
      'Certidão negativa federal',
      'Certidão FGTS',
      'Atestado de capacidade técnica',
      'Contrato social',
      'Proposta comercial assinada',
    ],
    custos: [
      { item: 'Horas técnicas (implantação)', valor: 'R$ 11.000' },
      { item: 'Setup de integrações / APIs', valor: 'R$ 4.500' },
      { item: 'Infraestrutura + LLM (12 meses)', valor: 'R$ 3.600' },
      { item: 'Suporte e manutenção', valor: 'R$ 2.900' },
    ],
    custoTotal: 'R$ 22.000',
    margem: '35%',
    propostaMin: 'R$ 41.000',
    propostaIdeal: 'R$ 48.000 – 54.000',
    risco: 'Baixo',
    concorrencia: 'Média',
    burocracia: 'Baixa',
    chance: 'Alta',
  },
  {
    id: 'op-377',
    orgao: 'Secretaria de Saúde do Estado do Piauí',
    cidade: 'Teresina',
    estado: 'PI',
    titulo:
      'Aquisição de assistente virtual para triagem e agendamento em unidades de saúde',
    objetoCurto: 'Assistente virtual · triagem · agendamento',
    modalidade: 'Pregão eletrônico',
    publicado: '30/05/2026',
    prazo: '21/06/2026',
    valor: 'R$ 178.000',
    valorNum: 178000,
    score: 79,
    status: 'boa',
    urgente: false,
    recomendacao:
      'Participar com parceiro — escopo técnico forte, mas exige atestado de grande porte.',
    tags: ['assistente virtual', 'IA', 'integração de sistemas'],
    resumo:
      'Implantação de assistente virtual para triagem inicial e agendamento integrado ao prontuário, com relatórios gerenciais. Contrato de 24 meses.',
    porQueCombina: [
      'Núcleo de IA conversacional e integração',
      'Valor relevante e contrato longo',
    ],
    porQueNao: [
      'Pregão exige atestado de porte e equipe dedicada',
      'Concorrência de fornecedores maiores',
    ],
    documentos: [
      'Atestado de capacidade técnica',
      'Balanço patrimonial',
      'Certidões fiscais',
      'Garantia de proposta',
    ],
    custos: [
      { item: 'Equipe dedicada (6 meses)', valor: 'R$ 64.000' },
      { item: 'Integração prontuário', valor: 'R$ 18.000' },
      { item: 'Infra + IA (24 meses)', valor: 'R$ 14.000' },
    ],
    custoTotal: 'R$ 96.000',
    margem: '30%',
    propostaMin: 'R$ 132.000',
    propostaIdeal: 'R$ 150.000 – 165.000',
    risco: 'Médio',
    concorrencia: 'Alta',
    burocracia: 'Média',
    chance: 'Média',
  },
  {
    id: 'op-355',
    orgao: 'Câmara Municipal de Juazeiro do Norte',
    cidade: 'Juazeiro do Norte',
    estado: 'CE',
    titulo:
      'Desenvolvimento de dashboard de transparência e BI para gestão de contratos',
    objetoCurto: 'Dashboard de transparência · BI',
    modalidade: 'Dispensa eletrônica',
    publicado: '01/06/2026',
    prazo: '11/06/2026',
    valor: 'R$ 38.500',
    valorNum: 38500,
    score: 72,
    status: 'boa',
    urgente: true,
    recomendacao:
      'Analisar — bom encaixe técnico, valor um pouco baixo para o escopo.',
    tags: ['dashboard', 'BI', 'transformação digital'],
    resumo:
      'Painel público de transparência com indicadores de contratos e BI interno para a controladoria. Implantação + 6 meses de suporte.',
    porQueCombina: [
      'Dashboards e BI são entregáveis recorrentes da AI Solution',
      'Dispensa eletrônica de ciclo curto',
    ],
    porQueNao: [
      'Valor estimado próximo do custo operacional',
      'Dados podem exigir limpeza pesada',
    ],
    documentos: ['Certidões fiscais', 'Contrato social', 'Proposta técnica'],
    custos: [
      { item: 'Desenvolvimento do painel', valor: 'R$ 16.000' },
      { item: 'Modelagem de dados / BI', valor: 'R$ 6.000' },
      { item: 'Suporte (6 meses)', valor: 'R$ 2.400' },
    ],
    custoTotal: 'R$ 24.400',
    margem: '28%',
    propostaMin: 'R$ 31.000',
    propostaIdeal: 'R$ 34.000 – 37.000',
    risco: 'Médio',
    concorrencia: 'Baixa',
    burocracia: 'Baixa',
    chance: 'Alta',
  },
  {
    id: 'op-341',
    orgao: 'Instituto Federal do Maranhão',
    cidade: 'São Luís',
    estado: 'MA',
    titulo:
      'Licenciamento de SaaS para automação de processos administrativos (workflow)',
    objetoCurto: 'SaaS · automação de workflow',
    modalidade: 'Pregão eletrônico',
    publicado: '28/05/2026',
    prazo: '25/06/2026',
    valor: 'R$ 96.000',
    valorNum: 96000,
    score: 64,
    status: 'possivel',
    urgente: false,
    recomendacao:
      'Analisar com cautela — exige certificações que ainda não temos.',
    tags: ['SaaS', 'automação', 'workflow'],
    resumo:
      'Plataforma SaaS para digitalizar fluxos administrativos com trilha de auditoria. Requer hospedagem em nuvem nacional e certificação de segurança.',
    porQueCombina: ['Automação de workflow é core', 'Modelo SaaS recorrente'],
    porQueNao: [
      'Exige certificação de segurança não disponível',
      'Hospedagem nacional específica',
    ],
    documentos: [
      'Certificação de segurança',
      'Atestado técnico',
      'Certidões fiscais',
      'Garantia',
    ],
    custos: [
      { item: 'Adaptação da plataforma', valor: 'R$ 28.000' },
      { item: 'Certificação / compliance', valor: 'R$ 22.000' },
      { item: 'Infra nacional (12m)', valor: 'R$ 12.000' },
    ],
    custoTotal: 'R$ 62.000',
    margem: '22%',
    propostaMin: 'R$ 80.000',
    propostaIdeal: 'R$ 86.000 – 92.000',
    risco: 'Alto',
    concorrencia: 'Média',
    burocracia: 'Alta',
    chance: 'Baixa',
  },
  {
    id: 'op-329',
    orgao: 'Prefeitura de Caucaia',
    cidade: 'Caucaia',
    estado: 'CE',
    titulo: 'Serviço de manutenção predial e limpeza de áreas comuns',
    objetoCurto: 'Manutenção predial · limpeza',
    modalidade: 'Pregão eletrônico',
    publicado: '29/05/2026',
    prazo: '19/06/2026',
    valor: 'R$ 240.000',
    valorNum: 240000,
    score: 12,
    status: 'baixa',
    urgente: false,
    recomendacao:
      'Descartar — objeto sem relação com o portfólio da AI Solution.',
    tags: ['facilities'],
    resumo: 'Contrato de facilities. Fora do escopo de tecnologia.',
    porQueCombina: [],
    porQueNao: ['Objeto não tecnológico', 'Sem aderência ao CNAE de software'],
    documentos: [],
    custos: [],
    custoTotal: '—',
    margem: '—',
    propostaMin: '—',
    propostaIdeal: '—',
    risco: 'Alto',
    concorrencia: 'Alta',
    burocracia: 'Alta',
    chance: 'Baixa',
  },
]

export const radarData: RadarData = { empresa, editais }
